import esbuild from 'esbuild';
import { copyFileSync, existsSync } from 'node:fs';

const production = process.argv.includes('production');

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Müslidian — Obsidian Granola plugin
*/`;

/** Plugin build (CommonJS, browser/Electron target — Obsidian loads CJS). */
const pluginBuild = {
  entryPoints: ['src/main.ts'],
  bundle: true,
  format: 'cjs',
  target: 'es2020',
  platform: 'browser',
  external: ['obsidian', 'electron', '@codemirror/*', '@lezer/*', 'codemirror'],
  outfile: 'dist/main.js',
  sourcemap: production ? false : 'inline',
  minify: production,
  banner: { js: banner },
  treeShaking: true,
  logLevel: 'info',
};

/** CLI build (ESM, Node 18+). */
const cliBuild = {
  entryPoints: ['bin/mueslidian.ts'],
  bundle: true,
  format: 'esm',
  target: 'node18',
  platform: 'node',
  outfile: 'dist/mueslidian.js',
  sourcemap: production ? false : 'inline',
  minify: production,
  banner: { js: banner },
  treeShaking: true,
  logLevel: 'info',
};

/** Copy manifest.json into dist/ so `make install` only needs to look there. */
function copyStaticAssets() {
  copyFileSync('manifest.json', 'dist/manifest.json');
  if (existsSync('styles.css')) copyFileSync('styles.css', 'dist/styles.css');
}

if (production) {
  await esbuild.build(pluginBuild);
  await esbuild.build(cliBuild);
  copyStaticAssets();
  console.log('Built dist/main.js, dist/mueslidian.js, dist/manifest.json');
} else {
  // Watch mode: copy static assets up-front, then keep esbuild contexts watching.
  copyStaticAssets();
  const ctxPlugin = await esbuild.context(pluginBuild);
  const ctxCli = await esbuild.context(cliBuild);
  await Promise.all([ctxPlugin.watch(), ctxCli.watch()]);
  console.log('Watching src/ and bin/ — Ctrl-C to stop.');
}
